---
title: "Summary statistics, tables and plots"
author: "Adrian Barnett"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "reports") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, error=FALSE, comment='', dpi=400)
library(dplyr)
library(tableone) # for giant baseline table
library(binom) # for CIs
library(xtable) # for latex tables
library(flextable)
library(ggplot2)
g.theme = theme_bw() + theme(panel.grid.minor = element_blank())

# get the data from 1_process.R
load('data/1_processed.RData')
# remove missing country to match analysis data
data = filter(data, !is.na(country))
#
data = mutate(data, year = as.numeric(format(published, '%Y'))) # add year published
```

## Top ten countries

```{r top_ten_countries}
countries = unlist(data$country)
tab = table(countries)
table = as.data.frame(tab) %>%
  mutate(percent = round(100*prop.table(Freq))) %>%
  arrange(desc(Freq)) %>%
  slice(1:10) %>%
  rename('Count'='Freq')
ftab = flextable(table) %>%
  theme_box() %>%
  autofit()
ftab
```

## Top ten subjects

```{r top_ten_subjects}
subjects = unlist(data$subjects)
tab = table(subjects)
table = as.data.frame(tab) %>%
  mutate(percent = round(100*prop.table(Freq))) %>%
  arrange(desc(Freq)) %>%
  slice(1:10) %>%
  rename('Count'='Freq')
ftab = flextable(table) %>%
  theme_box() %>%
  autofit()
ftab
```

## Summary table

```{r summary}
# Create a TableOne object
vars = c('review_available','year','n_authors','time_between','journal','type','citations','retracted') # 
n_vars = c('year','n_authors','time_between','citations') # number variables
tab2 <- CreateTableOne(vars = vars, 
                       data = data, 
                       factorVars = NULL, 
                       test = FALSE, 
                       includeNA = TRUE,
                       addOverall = FALSE) # no total column
print(tab2, # print version for Word document
      nonnormal = n_vars, # use median instead of mean
      catDigits = 1, # no longer allows 0 
      contDigits = 1, 
      explain = TRUE, 
      showAllLevels = TRUE,
      formatOptions = list(big.mark = ""))
# export to latex
m2 = data.frame(print(tab2, 
                      printToggle = FALSE,
                      nonnormal = n_vars, # use median instead of mean
                      catDigits = 1, # no longer allows 0 
                      contDigits = 1, 
                      explain = TRUE, 
                      showAllLevels = TRUE,
                      formatOptions = list(big.mark = ""))) %>%
  tibble::rownames_to_column(var = "var")
print(xtable(m2), include.rownames=FALSE, hline.after=FALSE, file = "results/2_big_table.tex")
```

## Openness over time

```{r time}
summary = group_by(data, year) %>%
  summarise(open = sum(review_available), 
            n = n(),
            p = open/n,
            lower = binom.confint(open, n, methods = 'asymptotic')$lower,
            upper = binom.confint(open, n, methods = 'asymptotic')$upper)
gplot = ggplot(data = summary, aes(x=year, y=p, ymin=lower,ymax=upper))+
  geom_point()+
  geom_line()+
  geom_ribbon(alpha=0.5)+
  xlab('Year')+
  ylab("Proportion choosing open peer review")+
  g.theme
gplot
```

The plot shows the yearly proportion and 95% confidence interval.

There was an increase over time in the proportion of authors choosing open review.