---
title: "Summary statistics for cases and controls"
author: "Adrian Barnett"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "reports") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, error=FALSE, comment='', dpi=400)
library(dplyr)
library(ggplot2)
library(ggtext) # for element_rmarkdown
g.theme = theme_bw() + theme(panel.grid.minor = element_blank())
source('R/plot_plus.R')

# get the elastic net estimates 
load('results/2_ests.RData')
# select the parameters at the parsimonious model threshold
best = filter(ests,
              abs(lambda - cvfit$lambda.1se) < 0.00001,
              abs(estimate) > 0.01 # must be bigger than a 1% change
              ) %>%
  select(-step, -dev.ratio)

# get the bayes estimates from aqua
load('results/3_model_estimates.RData')
table = mutate(table, row=as.numeric(row))
colnames = data.frame(var = colnames) %>% mutate(row = 1:n())
table = left_join(table, colnames, by='row')

# need indices for Bayes results
index_subjects = 1:67
index_countries = 68:104
index_type = 105:110
index_domain = 111:117
```


## Countries

```{r, fig.height = 7}
cplot = plot_plus(elastic = best, 
                  estring = '^country', 
                  bayes_table = table,
                  index = index_countries,
                  colour_names = TRUE,
                  acolors = c('dodgerblue','skyblue'))
cplot
# export
ggsave('figures/3_country_plus.jpeg', cplot, width=4, height=5, units='in', dpi = 500)
```

## Subjects

```{r, fig.height = 7}
splot = plot_plus(elastic = best, 
                  estring = '^subject', 
                  bayes_table = table,
                  index = index_subjects,
                  colour_names = TRUE,
                  acolors = c('darkorange1','darkorange4'))
splot
# export
ggsave('figures/3_subjects_plus.jpeg', splot, width=4, height=5, units='in', dpi = 500)
```


## Types

```{r, fig.height = 2.2}
tplot = plot_plus(elastic = best, 
                  estring = '^type', 
                  bayes_table = table,
                  index = index_type,
                  expand = 0.1,
                  acolors = c('darkseagreen3','darkseagreen3'))
tplot
# export
ggsave('figures/3_types_plus.jpeg', tplot, width=4, height=4, units='in', dpi = 500)
```

## Email domain

```{r, fig.height = 3}
dplot = plot_plus(elastic = best, 
                  estring = '^domain', 
                  bayes_table = table,
                  index = index_domain,
                  expand = 0.1,
                  acolors = c('darkorchid3','darkorchid3'))
dplot
# export
ggsave('figures/3_email_plus.jpeg', dplot, width=4, height=4, units='in', dpi = 500)
```

## Check convergence

```{r}
index = which(colnames(mcmc_out$samples$chain1) == 'intercept')
plot(mcmc_out$samples$chain1[,index])
```
