# 99_excluded.R
# types of paper to exclude, called by 0_read_xml_data.R
# August 2025

exclude_types = c("Best Practice",
                  "Book Review/Science in the Media", 
                  "Book Review",
                  'Collection Review',
                  "Community Page",
                  'Consensus View',
                  "Correction",
                  'Correspondence',
                  "Correspondence and Other Communications",
                  "Debate",
                  "Deep Reads",
                  'Editorial',
                  'Editorial Note',
                  "Education",
                  "Essay",
                  'Expert Commentary',
                  "Expression of Concern",
                  "Feature",
#                  'Formal Comment', # some are peer reviewed
                  'From Innovation to Application',
                  'Guidelines and Guidance',
                  'Health in Action',
                  "Historical and Philosophical Perspectives",
                  'Historical Profiles and Perspectives',
                  "Interview",
                  "Journal Club", 
                  'Learning Forum',
                  'Message from ISCB',
                  'Message from PLoS',
'Message from the PLoS Founders',
                  'Message from the Founders',
                  'Neglected Diseases',
                  'Obituary',
                  "Opinion",
"Opinion Piece",
"Open Highlights",
"Pearls",
                  "Perspective",
'Photo Quiz',
                  'Policy Forum',
                  'Policy Platform',
                  'Quiz',
                  "Primer",
                  'Research in Translation',
                  'Research Matters',
                  "Retraction",
                  "Special report",
                  'Special Report',
                  'Student Forum',
                  'Symposium',
                  'Synopsis',
                  'The PLoS Medicine Debate',
                  'Topic Page',
                  "Unsolved Mystery",
                  'Viewpoints'
                  )
